### ISSUE TITLE
AnimateColor is Deprecated change to tanimator.animatecolor

### ISSUE THREAD

**Issue by rioda78** [yordanhutama/xcorp#1]
untuk kode yang menggunakan animatcolor dan animatedloat sudah deprecated.
saran
1. tambah use fmx.ani
2. change this code 
tcontrol(Sender).AnimateColor('Fill.Color', $FF181818, 0.2, TAnimationType.InOut, TInterpolationType.Circular);
to this code
  TAnimator.AnimateColor(TControl(Sender),'Fill.Color', $FF181818, 0.2, TAnimationType.InOut, TInterpolationType.Circular );
3. change this code
rmain.AnimateFloat('Width', 302, 0.2, TAnimationType.InOut, TInterpolationType.Circular);
to this
TAnimator.AnimateFloat(rmain,'Width', 302, 0.2, TAnimationType.InOut, TInterpolationType.Circular);
4. selesai
5. isu deprecated selesai.
semoga membantu

**Comment by yordanhutama** [comment]
Terimakasih rioda, aku baru belajar delphi hehe, saya terapkan code nya, terimakasih banyak
